export const movieItems = [
    {
        title: "The Shawshank Redemption",
        year: "1994",
        genre: ["Drama"],
        country: ["USA"],
        imdb_rating: 9.3,
        oscar_nominations: 7,
        oscar_winning: 0,
        cast: ["Tim Robbins", "Morgan Freeman"],
        language: ["English"],
        oscar_nominations_list: [
            "Best Picture",
            "Best Actor",
            "Best Supporting Actor",
            "Best Director",
            "Best Adapted Screenplay",
            "Best Cinematography",
            "Best Film Editing",
        ],
        oscar_winning_list: [],
    },
    {
        title: "The Godfather",
        year: "1972",
        genre: ["Crime", "Drama"],
        country: ["USA"],
        imdb_rating: 9.2,
        oscar_nominations: 11,
        oscar_winning: 3,
        cast: ["Marlon Brando", "Al Pacino"],
        language: ["English", "Italian"],
        oscar_nominations_list: [
            "Best Picture",
            "Best Actor",
            "Best Supporting Actor",
            "Best Director",
            "Best Adapted Screenplay",
            "Best Cinematography",
            "Best Costume Design",
            "Best Production Design",
            "Best Film Editing",
            "Best Original Score",
            "Best Original Song",
        ],
        oscar_winning_list: [
            "Best Picture",
            "Best Actor",
            "Best Adapted Screenplay",
        ],
    },
    {
        title: "The Dark Knight",
        year: "2008",
        genre: ["Action", "Crime", "Drama"],
        country: ["USA", "UK"],
        imdb_rating: 9,
        oscar_nominations: 8,
        oscar_winning: 2,
        cast: ["Christian Bale", "Heath Ledger"],
        language: ["English"],
        oscar_nominations_list: [
            "Best Picture",
            "Best Supporting Actor",
            "Best Cinematography",
            "Best Film Editing",
            "Best Sound",
            "Best Sound Effects",
            "Best Visual Effects",
            "Best Original Score",
        ],
        oscar_winning_list: ["Best Supporting Actor", "Best Sound Effects"],
    },
    {
        title: "Pulp Fiction",
        year: "1994",
        genre: ["Crime", "Drama"],
        country: ["USA"],
        imdb_rating: 8.9,
        oscar_nominations: 7,
        oscar_winning: 1,
        cast: ["John Travolta", "Uma Thurman"],
        language: ["English"],
        oscar_nominations_list: [
            "Best Picture",
            "Best Actor",
            "Best Supporting Actor",
            "Best Director",
            "Best Original Screenplay",
            "Best Film Editing",
            "Best Original Score",
        ],
        oscar_winning_list: ["Best Original Screenplay"],
    },
    {
        title: "Inception",
        year: "2010",
        genre: ["Action", "Adventure", "Sci-Fi"],
        country: ["USA", "UK", "Japan"],
        imdb_rating: 8.8,
        oscar_nominations: 8,
        oscar_winning: 4,
        cast: ["Leonardo DiCaprio", "Joseph Gordon-Levitt"],
        language: ["English", "Japanese", "French"],
        oscar_nominations_list: [
            "Best Picture",
            "Best Original Screenplay",
            "Best Cinematography",
            "Best Film Editing",
            "Best Sound",
            "Best Sound Effects",
            "Best Visual Effects",
            "Best Original Score",
        ],
        oscar_winning_list: [
            "Best Original Score",
            "Best Visual Effects",
            "Best Sound",
            "Best Sound Effects",
        ],
    },
    {
        title: "Goodfellas",
        year: "1990",
        genre: ["Biography", "Crime", "Drama"],
        country: ["USA"],
        imdb_rating: 8.7,
        oscar_nominations: 6,
        oscar_winning: 1,
        cast: ["Ray Liotta", "Robert De Niro"],
        language: ["English", "Italian", "Spanish"],
        oscar_nominations_list: [
            "Best Picture",
            "Best Supporting Actor",
            "Best Director",
            "Best Adapted Screenplay",
            "Best Film Editing",
            "Best Original Score",
        ],
        oscar_winning_list: ["Best Supporting Actor"],
    },
    {
        title: "The Lord of the Rings: The Fellowship of the Ring",
        year: "2001",
        genre: ["Action", "Adventure", "Drama"],
        country: ["New Zealand", "USA"],
        imdb_rating: 8.8,
        oscar_nominations: 13,
        oscar_winning: 4,
        cast: ["Elijah Wood", "Ian McKellen"],
        language: ["English", "Sindarin", "Quenya"],
        oscar_nominations_list: [
            "Best Picture",
            "Best Actor",
            "Best Supporting Actor",
            "Best Director",
            "Best Adapted Screenplay",
            "Best Film Editing",
            "Best Original Score",
            "Best Art Direction",
            "Best Costume Design",
            "Best Makeup",
            "Best Sound",
            "Best Visual Effects",
        ],
        oscar_winning_list: [
            "Best Original Score",
            "Best Visual Effects",
            "Best Art Direction",
            "Best Makeup",
        ],
    },
    {
        title: "The Lord of the Rings: The Two Towers",
        year: "2002",
        genre: ["Action", "Adventure", "Drama"],
        country: ["New Zealand", "USA"],
        imdb_rating: 8.7,
        oscar_nominations: 6,
        oscar_winning: 2,
        cast: ["Elijah Wood", "Ian McKellen"],
        language: ["English", "Sindarin", "Quenya"],
        oscar_nominations_list: [
            "Best Picture",
            "Best Supporting Actor",
            "Best Director",
            "Best Adapted Screenplay",
            "Best Film Editing",
            "Best Original Score",
        ],
        oscar_winning_list: ["Best Original Score", "Best Visual Effects"],
    },
   
    {
        title: "Schindler's List",
        year: "1993",
        genre: ["Biography", "Drama", "History"],
        country: ["USA"],
        imdb_rating: 8.9,
        oscar_nominations: 12,
        oscar_winning: 7,
        cast: ["Liam Neeson", "Ben Kingsley"],
        language: ["English", "Polish", "German"],
        oscar_nominations_list: [
            "Best Picture",
            "Best Actor",
            "Best Supporting Actor",
            "Best Director",
            "Best Adapted Screenplay",
            "Best Cinematography",
            "Best Film Editing",
            "Best Original Score",
            "Best Art Direction",
            "Best Costume Design",
            "Best Makeup",
            "Best Sound",
        ],
        oscar_winning_list: [
            "Best Picture",
            "Best Director",
            "Best Adapted Screenplay",
            "Best Original Score",
            "Best Cinematography",
            "Best Film Editing",
            "Best Art Direction",
        ],
    },
    {
        title: "The Lord of the Rings: The Return of the King",
        year: "2003",
        genre: ["Action", "Adventure", "Drama"],
        country: ["New Zealand", "USA"],
        imdb_rating: 8.9,
        oscar_nominations: 11,
        oscar_winning: 11,
        cast: ["Elijah Wood", "Viggo Mortensen"],
        language: ["English", "Sindarin"],
        oscar_nominations_list: [
            "Best Picture",
            "Best Actor",
            "Best Supporting Actor",
            "Best Director",
            "Best Adapted Screenplay",
            "Best Cinematography",
            "Best Film Editing",
            "Best Original Score",
            "Best Art Direction",
            "Best Costume Design",
            "Best Makeup",
            "Best Sound",
            "Best Visual Effects",
        ],
        oscar_winning_list: [
            "Best Picture",
            "Best Director",
            "Best Adapted Screenplay",
            "Best Original Score",
            "Best Cinematography",
            "Best Film Editing",
            "Best Art Direction",
            "Best Costume Design",
            "Best Makeup",
            "Best Sound",
            "Best Visual Effects",
        ],
    },
    {
        title: "Fight Club",
        year: "1999",
        genre: ["Drama"],
        country: ["USA"],
        imdb_rating: 8.8,
        oscar_nominations: 1,
        oscar_winning: 0,
        cast: ["Brad Pitt", "Edward Norton"],
        language: ["English"],
        oscar_nominations_list: ["Best Sound Effects"],
        oscar_winning_list: [],
    },
    {
        title: "Forrest Gump",
        year: "1994",
        genre: ["Drama", "Romance"],
        country: ["USA"],
        imdb_rating: 8.8,
        oscar_nominations: 13,
        oscar_winning: 6,
        cast: ["Tom Hanks", "Robin Wright"],
        language: ["English"],
        oscar_nominations_list: [
            "Best Picture",
            "Best Actor",
            "Best Supporting Actor",
            "Best Director",
            "Best Adapted Screenplay",
            "Best Film Editing",
            "Best Original Score",
            "Best Art Direction",
            "Best Costume Design",
            "Best Makeup",
            "Best Sound",
            "Best Visual Effects",
            "Best Original Song",
        ],
        oscar_winning_list: [
            "Best Picture",
            "Best Actor",
            "Best Director",
            "Best Adapted Screenplay",
            "Best Original Score",
            "Best Visual Effects",
        ],
    },
    {
        title: "The Matrix",
        year: "1999",
        genre: ["Action", "Sci-Fi"],
        country: ["Australia", "USA"],
        imdb_rating: 8.7,
        oscar_nominations: 4,
        oscar_winning: 4,
        cast: ["Keanu Reeves", "Laurence Fishburne"],
        language: ["English"],
        oscar_nominations_list: [
            "Best Film Editing",
            "Best Sound",
            "Best Sound Effects",
            "Best Visual Effects",
        ],
        oscar_winning_list: [
            "Best Film Editing",
            "Best Sound",
            "Best Sound Effects",
            "Best Visual Effects",
        ],
    },
    
    
    {
        title: "The Empire Strikes Back",
        year: "1980",
        genre: ["Action", "Adventure", "Fantasy"],
        country: ["USA"],
        imdb_rating: 8.7,
        oscar_nominations: 3,
        oscar_winning: 2,
        cast: ["Mark Hamill", "Harrison Ford"],
        language: ["English"],
        oscar_nominations_list: [
            "Best Art Direction",
            "Best Original Score",
            "Best Sound",
        ],
        oscar_winning_list: ["Best Art Direction", "Best Original Score"],
    },
];

